name: mpsadjoint
channels:
  - conda-forge
  - defaults
dependencies:
    - python
    - pip
    - fenics
    - scipy
    - numpy
    - matplotlib
    - mpi4py
    - cyipopt
    - opencv-python<=4.7.0.72
    - dask
    - dolfin-adjoint
    - cardiac-mps
